meta-microblaze: rename mesa bbappend
Issue: LIN1025-5553

The bb files for mesa in oe-core layers has been renamed to mesa.bb
which have no "_" anymore. So rename mesa_%.bbappend to mesa.bbappend
to fix the error:
    ERROR: No recipes in default available for:
    layers/meta-xilinx/meta-microblaze/recipes-graphics/mesa/mesa_%.bbappend

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>