meta-xilinx-core: drop xilinx-wic bbclass
Issue: LINUXEXEC-37078

We need to drop the xilinx-wic bbclass introduced in v2025.2, because it
is a scarthgap version wic implementation and will mess up the walnascar
version.

This is to fix the following build error:

    |   File "layers/meta-xilinx/meta-xilinx-core/scripts/lib/wic/partition.py", line 189, in prepare
    |     plugin.do_prepare_partition(self, srcparams_dict, creator,
    |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                                 cr_workdir, oe_builddir, bootimg_dir,
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                                 kernel_dir, rootfs_dir, native_sysroot, sector_size=self.sector_size)
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | TypeError: BootimgPartitionPlugin.do_prepare_partition() got an unexpected keyword argument 'sector_size'

(LOCAL REV: NOT UPSTREAM) - WRLinux Specific

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>