meta-xilinx-core: comment out the config file for xlnx qemu
Issue: LINUXEXEC-33488

WRLinux doesn't support xlnx-qemu, so comment out the config file from
machine config file to fix the building error:

    ERROR: Nothing PROVIDES 'qemu-devicetrees-native'. Close matches:
	qemu-helper-native
    ERROR: Required build target 'wrlinux-image-std' has no buildable providers.

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>