zocl: pass a new -fmacro-prefix-map replacement to ${CC}
Issue: LINUXEXEC-37078

When buildpath is in ERROR_QA, zocl fails to build with the following
error:
    ERROR: zocl-202520.2.20.0-r0 do_package_qa: QA Issue: File /usr/lib/modules/6.12.64-yocto-standard/updates/zocl.ko in package kernel-module-zocl-6.12.41-yocto-standard contains reference to TMPDIR [buildpaths]
    ERROR: zocl-202520.2.20.0-r0 do_package_qa: Fatal QA errors were found, failing task.

Normally, the gcc option "-fmacro-prefix-map=old=new" will replace all
absolute path of files as "old" with a relative path as "new". But when
another option "-fcanon-prefix-map" is passed along with the option
"-fmacro-prefix-map", only paths which precisely match with the "old"
string will be replaced and the paths like "<old_string>/../../" will
remain unchanged.

There are some paths like "${S}/../../../common/drv/kds_hwctx.c" in
zocl.ko. To fix this, add a new comparison "${S}/../../../" to
"-fmacro-prefix-map".

(LOCAL REV: NOT UPSTREAM) -- WRLinux specific

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>