meta-xilinx-standalone: libgcc: copy specs files for cortexa9
Issue: LINUXEXEC-37078

When libgcc updates to 14.3.0, there are some specs files are created
for cortexa9 architecture, we need to add them to FILES:${PN}-dev to
avoid the following error:

    ERROR: mc:zynq-zc702-sdt-full-cortexa9-fsbl:libgcc-14.3.0-r0 do_package: QA Issue: libgcc: Files/directories were installed but not shipped in any package:
    /usr/lib/sync-none.specs
    /usr/lib/sync-dmb.specs
    /usr/lib/sync-cp15dmb.specs
    Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
    libgcc: 3 installed and not shipped files. [installed-vs-shipped]

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>