libxil: remove MACHINE_FEATURES component mali400 and secure-boot
Issue: LINUXEXEC-37078

The recipe for libxil uses MACHINE_FEATURES as PACKAGECONFIG and
this will result the following error since some MACHINE_FEATURES
components like "mali400" are not in PACKAGECONFIG flags list:
    ERROR: mc:wrlinux-zynqmp-zcu102-sdt-microblaze-pmu:libxil-2025.2+git-r0 do_recipe_qa: QA Issue: libxil: invalid PACKAGECONFIG(s): mali400 [invalid-packageconfig]
    ERROR: mc:wrlinux-zynqmp-zcu102-sdt-microblaze-pmu:libxil-2025.2+git-r0 do_recipe_qa: Fatal QA errors were found, failing task.

Remove mali400 and secure-boot from MACHINE_FEATURES to fix this issue.

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>