libxil: remove normal MACHINE_FEATURES components
Issue: LINUXEXEC-36549

The recipe for libxil uses MACHINE_FEATURES as PACKAGECONFIG and
this will result the following error since some MACHINE_FEATURES
components like "ext3 keyboard" are not in PACKAGECONFIG flags list:

ERROR: mc:versal-vck190-sdt-seg-microblaze-pmc:libxil-2025.1+git-r0 do_recipe_qa: QA Issue: libxil: invalid PACKAGECONFIG(s): ext3 keyboard network pci usbgadget usbhost vfat [invalid-packageconfig]
ERROR: mc:versal-vck190-sdt-seg-microblaze-pmc:libxil-2025.1+git-r0 do_recipe_qa: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: tmp-versal-vck190-sdt-seg-microblaze-pmc/work/microblazeel-v10.0-bs-cmp-re-mh-div-xilinx-elf/libxil/2025.1+git/temp/log.do_recipe_qa.1940455
ERROR: Task (mc:versal-vck190-sdt-seg-microblaze-pmc:meta-xilinx/meta-xilinx-standalone-sdt/recipes-libraries/embeddedsw/libxil_2025.1.bb:do_recipe_qa) failed with exit code '1'

The reason why we don't list all available flags but only remove
all unavailable flags is that the PACKAGECONFIG[flag] value are in
the config file versal-vck190-sdt-seg-microblaze-psm-libxil.conf
which is generated by gen-machineconf script. The values are dynamically
generated from the xsa file which depends on the design of customer.

(LOCAL REV: NOT UPSTREAM) -- WRLinux specific

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>