meta-xilinx-mali400: gstreamer: drop egl surfaceless support
Issue: LINUXEXEC-35126

When enabling mali400 GPU support, building gstreamer1.0-plugins-base
will trigger the following error:

    ../gst-plugins-base-1.24.6/gst-libs/gst/gl/egl/gstgldisplay_egl.c: In function 'gst_gl_display_egl_get_from_native':
    ../gst-plugins-base-1.24.6/gst-libs/gst/gl/egl/gstgldisplay_egl.c:241:39: error: 'EGL_PLATFORM_SURFACELESS_MESA' undeclared (first use in this func    tion)
    241 |     ret = _gst_eglGetPlatformDisplay (EGL_PLATFORM_SURFACELESS_MESA,
        |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is because the header file eglext.h which is provided by mali400
package don't support egl surfaceless. So reverting the commit
e1ca5754089df467 ("gl: add support for surfaceless display in GstGL") in
    https://gitlab.freedesktop.org/gstreamer/gstreamer.git

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>